apiVersion: v1
kind: Service
metadata: 
  namespace: crawler
  name: crawler-service
spec:
  type: ClusterIP
  selector:
    app: synergychat-crawler
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
